const mongoose = require('mongoose');
const datos2018Schema = mongoose.Schema(
    { 
        P1_Pais : { type : Number},
        P2_Edad: { type : Number},
        P2A_Edad_Rangos : { type : Number} ,
        P3_Genero: { type : Number} ,
        P4_Nivel_Educativo : { type : Number} ,
        P5_Ocupacion : { type : Number} ,
        P6_Ingreso : { type : Number} ,
        P7_Estrato: { type : Number},
        P6_P7_NSE_Total : { type : Number},
        P8_Zona_Res: { type : Number},
        P9_Frec_Int : { type : Number},
        P10A_Correo: { type : Number},
        P10B_Noticias: { type : Number},
        P10C_Direcciones: { type : Number},
        P10D_Entretenimiento: { type : Number},
        P10E_Pagos: { type : Number},
        P10F_Informacion: { type : Number},
        P10G_Comprar: { type : Number},
        P11A_A1_Prefiero_ver_lo_que_compro: { type : Number} ,
        P11A_A2_Miedo_a_entregar_mi_informacion_personal: { type : Number} ,
        P11A_A3_Desconfianza_en_la_forma_de_pago: { type : Number} ,
        P11A_A4_Miedo_a_ser_estafado_enganiado: { type : Number} ,
        P11A_A5_Desconfio_de_la_informacion_que_ofrecen_las_tiendas_vendedores_en_linea: { type : Number} ,
        P11A_A6_Desconocimiento_falta_de_informacion: { type : Number} ,
        P11A_A7_Prefiero_hablar_con_un_vendedor: { type : Number} ,
        P11A_A8_Dificultad_para_recibir_el_pedido_que_no_llegue_el_pedido: { type : Number} ,
        P11A_A9_Costos_del_envio: { type : Number} ,
        P11A_A10_Lo_he_intentado_sin_exito: { type : Number} ,
        P11A_A11_Malas_referencias_de_otras_personas : { type : Number} ,
        P11A_A12_Otra: { type : Number} ,
        P11A_A13_Especifique_cual: { type : String} ,
        P11B_B1_Mas_informacion_de_como_realizar_las_compras: { type : Number} ,
        P11B_B2_Contar_con_garantia_de_devolucion_o_cambio: { type : Number} ,
        P11B_B3_Si_garantizan_confidencialidad_en_la_informacion_suministrada: { type : Number} ,
        P11B_B4_Atencion_al_cliente_en_caso_de_errores_en_el_proceso_de_compra: { type : Number} ,
        P11B_B5_Asistencia_durante_el_proceso_de_compra: { type : Number} ,
        P11B_B6_Tutoriales_o_induccion_para_realizar_la_compra: { type : Number} ,
        P11B_B7_Mayor_variedad_de_la_oferta: { type : Number} ,
        P11B_B8_Puntualidad_en_la_entrega: { type : Number} ,
        P11B_B9_Bajos_costos_del_envio: { type : Number} ,
        P11_B10_Otra: { type : Number} ,
        P11_Compras: { type : Number},
        P11_Rec_Compras: { type : Number},
        P12A_Productos_tiendas_ecuatorianas: { type : Number},
        P12B_Productos_tiendas_internacionales: { type : Number},
        P12C_Servicios_en_tiendas_ecuatorianas: { type : Number},
        P12D_Servicios_en_tiendas_internacionales: { type : Number},
        P13A_Amigos: { type : Number},
        P13B_Web : { type : Number} ,
        P13C_Opiniones : { type : Number} ,
        P13D_RRSS: { type : Number} ,
        P13E_Buscadores: { type : Number} ,
        P13F_Tienda_fisica: { type : Number} ,
        P13G_Comentarios : { type : Number} ,
        P14_Ir_a_la_tienda_fisica: { type : Number},
        P15A_Hogar: { type : Number},
        P15B_Empresa_trabajo: { type : Number} ,
        P15C_En_movilidad: { type : Number} ,
        P15D_Puntos_de_acceso_publico : { type : Number} ,
        P15E_En_las_propias_tiendas : { type : Number} ,
        P16B_P1_Ropa : { type : Number},
        P16B_P2_Calzado : { type : Number},
        P16B_P3_Accesorios: { type : Number},
        P16B_P4_Cosmeticos: { type : Number},
        P16B_NP1_Celulares : { type : Number},
        P16B_NP2_Computacion   : { type : Number},
        P16B_NP3_Electronicos : { type : Number},
        P16B_NP4_Libros  : { type : Number},
        P16B_NP5_Medicamentos: { type : Number},
        P16B_NP6_Juguetes : { type : Number},
        P16_H1_Supermercado   : { type : Number},
        P16_H2_Mobiliario : { type : Number},
        P16_H3_Construccion : { type : Number},
        P16_S1_Pasajes: { type : Number},
        P16S2_Tiquetes_entradas: { type : Number},
        P16_S3_Hoteles: { type : Number},
        P16S4_Educacion_Online : { type : Number},
        P16S5_Comida : { type : Number},
        P17A_Conectarse : { type : Number},
        P17B_Comprar : { type : Number},
        P17_1A_APPMarca: { type : Number} ,
        P17_1B_Web: { type : Number} ,
        P17_1C_Marketplace: { type : Number} ,
        P17_1D_APPTiendas: { type : Number} ,
        P18A_C_Facilidad: { type : Number} ,
        P18A_C_Comodidad: { type : Number} ,
        P18A_C_Rapidez: { type : Number} ,
        P18A_C_Seguridad: { type : Number} ,
        P18A_C_Conveniencia : { type : Number} ,
        P18B_T_Facilidad: { type : Number} ,
        P18B_T_Comodidad: { type : Number} ,
        P18B_T_Rapidez: { type : Number} ,
        P18B_T_Seguridad: { type : Number} ,
        P18B_T_Conveniencia : { type : Number} ,
        P18C_TV_Facilidad: { type : Number} ,
        P18C_TV_Comodidad: { type : Number} ,
        P18C_TV_Rapidez: { type : Number} ,
        P18C_TV_Seguridad: { type : Number} ,
        P18C_TV_Conveniencia : { type : Number} ,
        P18C_PORT_Facilidad: { type : Number},
        P18C_PORT_Comodidad: { type : Number},
        P18C_PORT_Rapidez: { type : Number},
        P18C_PORT_Seguridad: { type : Number} ,
        P18C_PORT_Conveniencia : { type : Number} ,
        P18PC_Facilidad: { type : Number} ,
        P18PC_Comodidad: { type : Number} ,
        P18PC_Rapidez: { type : Number} ,
        P18PC_Seguridad: { type : Number} ,
        P18PC_Conveniencia : { type : Number} ,
        P19A_Visa : { type : Number},
        P19A_Master: { type : Number} ,
        P19A_Dinners: { type : Number} ,
        P19A_American: { type : Number } ,
        P19B_Visa : { type : Number } ,
        P19B_Master: { type : Number } ,
        P19B_Dinners: { type : Number } ,
        P19B_American: { type : Number } ,
        P20_BP_Amazon: { type : Number } ,
        P20_BP_Ebay: { type : Number } ,
        P20_BP_Portal_del_fabricante: { type : Number } ,
        P20_BP_Ali_Express: { type : Number } ,
        P20_BP_Particulares_Vendedores : { type : Number } ,
        P20_BP_Falabella: { type : Number } ,
        P20_BP_Mercado_Libre: { type : Number } ,
        P20_BP_OLX: { type : Number } ,
        P20_BP_Otros : { type : Number } ,
        P20_BP_Cual : { type : String } ,
        P21_BP_DePrati: { type : Number } ,
        P21_BP_Creditos_Economicos: { type : Number } ,
        P21_BP_Linio : { type : Number } ,
        P21_BP_Wish_Ecuador : { type : Number } ,
        P21_BP_No_compro_en_linea_en_tiendas_ecuatorianas : { type : Number } ,
        P21_BP_Otros : { type : Number } ,
        P21_Otros_cual: { type : String } ,
        P22_BNP_Amazon: { type : Number } ,
        P22_BNP_Ebay: { type : Number } ,
        P22_BNP_Portal_del_fabricante: { type : Number } ,
        P22_BNP_Ali_Express: { type : Number } ,
        P22_BNP_Particulares_Vendedores_independientes: { type : Number } ,
        P22_BNP_Sony: { type : Number } ,
        P22_BNP_Mercado_Libre: { type : Number } ,
        P22_BNP_OLX: { type : Number } ,
        P22_BNP_Otros : { type : Number } ,
        P22_BNP_Otros_cual: { type : String } ,
        P23_BP_DePrati: { type : Number } ,
        P23_BP_Comandato: { type : Number } ,
        P23_BP_Creditos_Economicos: { type : Number } ,
        P23_BP_Claro: { type : Number } ,
        P23_BP_Telefonica_Movistar: { type : Number } ,
        P23_BP_Disensa: { type : Number } ,
        P23_BP_Linio : { type : Number } ,
        P23_BP_Wish_Ecuador: { type : Number } ,
        P23_BP_No_compro_en_linea_en_tiendas_ecuatorianas : { type : Number } ,
        P23_BP_Otros : { type : Number } ,
        P23_Otro_Cual: { type : String } ,
        P24_Serv_Despegar: { type : Number } ,
        P24_Serv_Tripadvisor: { type : Number } ,
        P24_Serv_Atrapalo: { type : Number } ,
        P24_Serv_Booking: { type : Number } ,
        P24_Serv_Cinemark: { type : Number } ,
        P24_Serv_Supercines: { type : Number },
        P24_Serv_Ticketshow: { type : Number } ,
        P24_Serv_Latam_Airlines: { type : Number } ,
        P24_Serv_Domicilios: { type : Number } ,
        P24_Serv_No_compro_en_linea_en_tiendas_ecuatorianas : { type : Number } ,
        P24_Serv_Otros : { type : Number } ,
        P24_Serv_Otros_Cual: { type : String } ,
        P24_1_ENV_DHL: { type : Number } ,
        P24_1_ENV_FedEx: { type : Number } ,
        P24_1_ENV_SERVIENTREGA: { type : Number } ,
        P24_1_ENV_Laarcourier: { type : Number } ,
        P24_1_ENV_UPS: { type : Number } ,
        P24_1_ENV_TNT: { type : Number } ,
        P24_1_ENV_Probox: { type : Number } ,
        P24_1_ENV_Correos_del_Ecuador: { type : Number } ,
        P24_1_ENV_Otros : { type : Number } ,
        P25_Abandono : { type : Number } ,
        P25A_Problemas : { type : Number } ,
        P25A_Precio: { type : Number } ,
        P25A_Dudas : { type : Number } ,
        P25A_No_respuesta : { type : Number } ,
        P25A_Tiempo_de_entrega : { type : Number } ,
        P25A_Mas_facil_personalmente: { type : Number } ,
        P25A_Complicado : { type : Number } ,
        ED1_Me_ayuda_a_realizar_mis_compras_de_forma_mas_eficiente: { type : Number } ,
        ED2_Es_mas_rapido_que_en_una_tienda_fisica : { type : Number } ,
        ED3_Es_mas_util_para_hacer_mis_compras_que_una_tienda_fisica: { type : Number } ,
        ED4_Me_permite_hacer_mejor_mis_compras : { type : Number } ,
        EE2_En_general_internet_es_facil_de_usar_para_hacer_mis_compras: { type : Number } ,
        EE3_Comprar_un_producto_a_traves_de_internet_no_requiere_demasiado_esfuerzo_mental: { type : Number } ,
        EE4_Realizar_compras_en_linea_es_claro_y_comprensible_para_mi : { type : Number } ,
        SI1_Las_personas_que_son_importantes_para_mi_piensan_que_yo_deberia_realizar_mis_compras_en_linea : { type : Number } ,
        SI2_Yo_pienso_que_la_gente_como_yo_tambien_hace_sus_compras_en_linea : { type : Number } ,
        SI4_Mis_amigos_familiares_y_colegas_me_animan_a_comprar_por_internet: { type : Number } ,
        CF3_Tengo_las_habilidades_necesarias_para_compras_por_internet: { type : Number },
        CF4_Yo_puedo_comprar_por_internet_aun_si_no_hay_nadie_cerca_que_pueda_ayudarme: { type : Number },
        CF5_Yo_pueda_comprar_razonablemente_bien_en_internet_por_mi_cuenta: { type : Number },
        CF6_Cuando_compro_por_Internet_hay_alguien_que_me_puede_ayudar_si_tengo_problemas_para_hacerlo: { type : Number },
        CF7_Comprar_o_hacer_transacciones_por_Internet_es_algo_que_me_gusta : { type : Number },
        MH1_Utilizar_internet_para_hacer_mis_compras_es_divertido: { type : Number },
        MH1_Utilizar_internet_para_hacer_mis_compras_es_agradable: { type : Number },
        HB2_El_uso_de_Internet_para_comprar_se_ha_convertido_en_una_habito_para_mi: { type : Number },
        SP1_No_me_preocupa_que_la_informacion_que_proporcione_la_hora_de_comprar_por_Internet_pueda_ser_utilizada_por_otras_personas: { type : Number },
        SP2_Siento_es_seguro_comprar_por_Internet: { type : Number },
        SP3_En_general_proporcionar_informacion_sobre_tarjetas_de_credito_en_los_sitios_Web_es_mas_arriesgado_que_una_compra_personal: { type : Number },
        CP1_En_general_las_tiendas_en_linea_son_dignas_de_confianza: { type : Number },
        CP2_En_general_las_tiendas_en_linea_cumplen_sus_promesas_y_acuerdos: { type : Number },
        CP4_En_general_las_tiendas_en_linea_ofrecen_buen_servicio: { type : Number },
        CP6_Confio_en_que_las_tiendas_en_linea_hacen_su_trabajo_correctamente: { type : Number },
        CP7_Mi_opinion_general_del_comercio_electronico_es_positiva: { type : Number },
        CP8_Prefiero_comprar_en_Internet_que_en_una_tienda_fisica: { type : Number },
        P27_Precios_mas_bajos: { type : Number },
        P27_Promociones_o_beneficios_adicionales: { type : Number } ,
        P27_Acumular_puntos_para_compras_futuras: { type : Number } ,
        P27_Trato_privilegiado: { type : Number } ,
        P28_Uber: { type : Number },
        P28_Cabify: { type : Number },
        P28_Easy_Taxi : { type : Number },
        P28_Sweet_Coffee: { type : Number },
        P28_KFC: { type : Number },
        P28_Wendys: { type : Number },
        P28_Mc_Donalds: { type : Number },
        P29_Lunes_a_Miercoles: { type : Number } ,
        P29_Jueves_y_Viernes: { type : Number } ,
        P29_Fin_de_Semana_feriado: { type : Number } ,
        P30_Conveniencia: { type : Number } ,
        P30_Ahorro_de_tiempo: { type : Number },
        P30_Ahorro_de_esfuerzo: { type : Number } ,
        P30_Rapidez: { type : Number } ,
        P30_Comodidad: { type : Number } ,
        P30_Satisfaccion_de_la_compra: { type : Number },
        P30_Confiabilidad: { type : Number } 
    
    })        

module.exports = mongoose.model('datos2018',datos2018Schema)